### ISSUE TITLE
[Issue] keep dropping framerate if install this mod

### ISSUE THREAD

**Issue by CoolLKKPS** [RT0405/TooManySuitsInWorldButtons#2]
same as topic, easy to reproduce

**Comment by Sourceshard** [comment]
After the recent update. FPS inside the ship drops heavily with this mod enabled. We are talking about a 60-70 FPS drop! Not sure what is wrong but I have removed it for now.

**Comment by RT0405** [comment]
I've found the problem and have uploaded the patch.

I forgot to set a value back to false, so it would just create two new buttons every frame. meaning that after 10 seconds of 60fps you would have 1200 buttons existing...

**Comment by RT0405** [comment]
thank you for notifying me and I apologize for the inconvenience
